# Generated by Django 5.0.2 on 2024-03-18 05:52

import django.db.models.deletion
import general.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('area_id', models.AutoField(max_length=30, primary_key=True, serialize=False)),
                ('area_location_latitude', models.DecimalField(decimal_places=30, max_digits=50)),
                ('area_location_longitude', models.DecimalField(decimal_places=30, max_digits=50)),
                ('area_name', models.CharField(max_length=50)),
                ('detected_people', models.IntegerField()),
                ('risk_point', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CCTV',
            fields=[
                ('cctv_id', models.AutoField(max_length=30, primary_key=True, serialize=False)),
                ('cctv_channel', models.IntegerField()),
                ('detected_people', models.IntegerField()),
                ('risk_point', models.CharField(max_length=10)),
                ('cctv_image', models.ImageField(blank=True, upload_to=general.models.CCTV.upload_to_func)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area', to='general.location')),
            ],
        ),
        migrations.CreateModel(
            name='Target_area',
            fields=[
                ('target_area_id', models.AutoField(max_length=30, primary_key=True, serialize=False)),
                ('risk_point', models.CharField(max_length=10)),
                ('cctv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cctv', to='general.cctv')),
            ],
        ),
        migrations.CreateModel(
            name='Target_area_points',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_x', models.DecimalField(decimal_places=30, max_digits=50)),
                ('point_y', models.DecimalField(decimal_places=30, max_digits=50)),
                ('target_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_area', to='general.target_area')),
            ],
        ),
    ]
