# Generated by Django 5.0.2 on 2024-03-20 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Target_area_points',
            new_name='Target_area_point',
        ),
    ]
