# Generated by Django 5.0.4 on 2024-04-29 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_rename_target_area_points_target_area_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cctv',
            name='cctv_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='location',
            name='area_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='target_area',
            name='target_area_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
