# Generated by Django 5.0.4 on 2024-05-02 00:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("general", "0003_alter_cctv_cctv_id_alter_location_area_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cctv",
            name="rtsp_url",
            field=models.CharField(blank=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name="cctv",
            name="cctv_image",
            field=models.ImageField(blank=True, upload_to="upload_to_func"),
        ),
    ]
