# Generated by Django 5.0.4 on 2024-05-02 04:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("general", "0004_cctv_rtsp_url_alter_cctv_cctv_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="cctv",
            name="http_url",
            field=models.CharField(blank=True, max_length=2048),
        ),
    ]
